# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Deploy Image
on:
  #  workflow_run:
  #   workflows: ["CI"]
  #  branches: [main]
  # types:
  #  - completed
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  Docker-Image:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Set up DockerHub QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: felixsteinke/private:FreshPlanner-Server

      - name: Image digest output
        run: echo ${{ steps.docker_build.outputs.digest }}
